config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
    root "static_pages#index"
    get "sessions/new"
    get "/index", to: "static_pages#index"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    get "/admin", to: "products#index"
    post "/login", to: "sessions#create"
    post "/signup", to: "users#create"
    delete "/logout", to: "sessions#destroy"
    post "/line_item", to: "line_items#create"
    # post "/product", to: "products#create"
    get "/product_details", to: "static_pages#product_details"
    get "admin/admin"
    get "admin/index"
    get "/checkorder", to: "line_items#index"
    get "/check", to: "line_items#show"
    get "/search", to: "static_pages#index"
    get "/change_quantity/:id", to: "line_items#change_quantity"
    get "/show_code_order", to: "orders#show_code_order"
    get "/show_order", to: "orders#show"
    post "/order_status", to: "orders#update"
    get "/create_order", to: "carts#index"
    resources :carts
    resources :products
    resources :users
    resources :orders
    resources :line_items
    resources :feedbacks
end

app/models/order.rb
class Order < ApplicationRecord
  VALID_PHONE = /[0-9]/i
  PAYMENT_TYPES = [I18n.t("order.select_1"), I18n.t("order.select_2")].freeze
  validates :name, :address, presence: true
  validates :pay_type, presence: true, inclusion: PAYMENT_TYPES
  validates :phone, length: {maximum: 10},
    format: {with: VALID_PHONE}, presence: true
  has_many :line_items, dependent: :destroy

  def add_line_items_from_cart cart
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end

  def status_finish
    update_columns status: "finish"
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include LineItemsHelper
  before_action :find_order, only: [:show, :edit, :update,
   :destroy, :show_code_order]

  def index
    @orders = Order.all.page(params[:page]).per Settings.limit_page_admin
  end

  def show
    @cart_code = LineItem.where order_id: params[:cart_code]
  end
  def show_code_order; end

  def new
    return redirect_to("/", notice: "Your cart is empty") if
      current_cart.line_items.empty?
    @order = Order.new
  end

  def edit; end

  def create
    @order = Order.new order_params

    @order.add_line_items_from_cart current_cart
    respond_to do |format|
      if @order.save
        Cart.destroy(session[:cart_id])
        session[:cart_id] = nil

        format.html do
          redirect_to show_code_order_path(id: @order),
            notice: I18n.t("order_controller.mess_order_success")
        end
        format.js
        format.json{render "/", status: :created}
      else
        format.html{render :new}
        format.json{render json: @order.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @order.destroy
    redirect_to orders_path
  end

  def update
    @orders = Order.all
    @order = Order.find_by id: params[:id]
    @order.status_finish
    respond_to do |format|
      format.html{redirect_to check_order_admin_path}
      format.js {}
    end
  end

  private

  def find_order
    @order = Order.find_by(id: params[:id])
  end

  def order_params
    params.require(:order).permit :name, :address, :phone, :pay_type
  end
end

app/views/orders/_form.html.erb
<%= form_with model: @order, local: true do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control col-md-6', size: 40 %>
    </div>
    <div class="form-group">
        <%= f.label :address %>
        <%= f.text_area :address, class: 'form-control col-md-6', rows: 3, cols: 40 %>
    </div>
    <div class="form-group">
        <%= f.label :Phone %>
        <%= f.text_field :phone, class: 'form-control col-md-6', size: 40 %>
    </div>
    <div class="form-group">
        <%= f.label :pay_type %>
        <%= f.select :pay_type, options_for_select(Order::PAYMENT_TYPES, prompt: t("select_0")), {}, { class: 'form-control col-md-6' } %>
    </div>

    <div class="actions">
        <%= f.submit (@order.new_record? ? "Place order" : "Save"), class: 'btn btn-primary pull-right', style: "margin-top: 5px;" %>
    </div>
<% end %>

app/views/orders/_form_finish.html.erb
<%= form_with model: @build_relationship do |f| %>
  <%= f.submit "Finish", class: "btn btn-primary" %>
<% end %>

app/views/orders/_orders.html.erb
 <% @orders.each do |order| %>
          <tr>
            <td><%= order.name %></td>
            <td><%= number_to_currency(order.line_items.sum{|item| item.quantity * (item.product.export_price * item.product.sale / 100)}, format: "%u %n", precision: 0) %></td>
            <td><span class="badge badge-warning"><%= order.status %></span></td>
            <td><%= order.address %></td>
            <td>
              <%= form_for order, remote: true do |f| %>
            <%= f.submit "Finish", class: "btn btn-primary"  %>
          <% end %>
              <%= link_to "Show", check_path(cart_code: order.id), class: "btn btn-info" %>
              <%= link_to "Edit", edit_order_path(order), class: "btn btn-primary" %>
              <%= link_to "Destroy", order, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
            </td>
          </tr>
        <% end %>

app/views/orders/edit.html.erb
<div class="container">
    <div class="row">
        <h1>Editing Order</h1>

        <div class="form-group">
            <%= render 'form', order: @order %>
        </div>

        <div class="form-group" style="clear: both;">
            <%= link_to 'Show Items', check_path(cart_code: @order.id), class: "btn btn-info" %>
            <%= link_to 'Back Manage Orders', orders_path, class: "btn btn-info"%>
        </div>
    </div>
</div>

app/views/orders/index.html.erb
<div class="container">
  <div class="row">
    <h1>Orders</h1>
    <div class="form-group">
      <%= link_to 'New Order', new_order_path, class: "btn btn-primary" %>
    </div>
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th class="col-md-2">Name</th>
          <th class="col-md-2">Price</th>
          <th class="col-md-2">Status</th>
          <th class="col-md-2">Address</th>
          <th class="col-md-3">Actions</th>
        </tr>
      </thead>

      <tbody class="order-index">
       <%= render "orders" %>
      </tbody>
    </table>
    <%= paginate @orders, theme: "twitter-bootstrap", window: 3 %>
  </div>
</div>

<br>

app/views/orders/new.html.erb
<div id="mainBody">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
      </div>
      <div class="col-md-6">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<div id="mainBody">
  <div class="container">
    <div class="row">
      <div class="span9">
        <%= link_to "Back", orders_path %>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th><%= t "view_cart.description" %></th>
              <th><%= t "view_cart.quantity" %></th>
              <th><%= t "view_cart.price" %></th>
              <th><%= t "view_cart.sale" %></th>
              <th><%= t "view_cart.total" %></th>
            </tr>
          </thead>
          <tbody>
            <%=  @cart_code.each do |a| %>
              <tr>
                <td><%= a.product.name %><br/>Color : black, Material : metal</td>
                <td><%= a.quantity %></td>
                <td><%= a.product.export_price %></td>
                <td><%= a.product.sale %></td>
                <td><%= a.total_price %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to "Back", orders_path %>
      </div>
    </div>
  </div>
</div>

app/views/orders/show_code_order.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Cart code: <%= @order.id %></strong>
</p>
<%= link_to "Back", root_path %>

app/views/orders/update.js.erb
$(".order-index").html("<%= j render("orders/orders") %>")
$.notify("update to order success",
  {
    type: 'success',
  }
)