config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
    root "static_pages#index"
    get "sessions/new"
    get "/index", to: "static_pages#index"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    get "/admin", to: "products#index"
    post "/login", to: "sessions#create"
    post "/signup", to: "users#create"
    delete "/logout", to: "sessions#destroy"
    post "/line_item", to: "line_items#create"
    # post "/product", to: "products#create"
    get "/product_details", to: "static_pages#product_details"
    get "admin/admin"
    get "admin/index"
    get "/checkorder", to: "line_items#index"
    get "/check", to: "line_items#show"
    get "/search", to: "static_pages#index"
    get "/change_quantity/:id", to: "line_items#change_quantity"
    get "/show_code_order", to: "orders#show_code_order"
    get "/show_order", to: "orders#show"
    post "/order_status", to: "orders#update"
    get "/create_order", to: "carts#index"
    resources :carts
    resources :products
    resources :users
    resources :orders
    resources :line_items
    resources :feedbacks
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy

  def add_product product_id
    current_item = line_items.find_by_product_id product_id
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build product_id: product_id
    end
    current_item
  end

  def total_price
    line_items.to_a.sum{|item| item.total_price}
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include LineItemsHelper
  before_action :find_cart, only: [:show, :update, :destroy]
  def index
    @carts = []
    return if session[:cart_id].nil?
    @carts << Cart.find_by_id(session[:cart_id])
    @product = Product.all.page(params[:page]).per Settings.limit_page_admin
  end

  def show
    @carts = []
    return if session[:cart_id].nil?
    @carts << Cart.find_by_id(session[:cart_id])
  end

  def new
    @cart = Cart.new
  end

  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html{redirect_to "/"}
        format.json{render :show, status: :created, location: @cart}
      else
        format.html{render :new}
        format.json{render json: @cart.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html{redirect_to "/"}
      format.json{head :no_content}
    end
  end

  private

  def find_cart
    return if @cart = Cart.find_by(id: params[:id])
    redirect_to root_path
  end

  def cart_params
    params.fetch(:cart, {})
  end
end

app/helpers/carts_helper.rb
module CartsHelper
  def find_order_id
    @find_order_id = LineItem.find_by cart_id: params[:id]
  end

  def hide_cart_if?
    find_order_id.present?
  end
end

app/views/carts/_cart.html.erb
<% current_cart.line_items.each do |a| %>
  <tr>
    <td class="col-md-2">
      <%= link_to image_tag(a.product.images.first.image, size: 100) %>
    <td class="col-md-4"><%= a.product.name %><br/>Color : black, Material : metal</td>
    <td class="col-md-3">
      <div class="form-group">
        <input class="pull-left quantity-item col-md-2" value="<%= a.quantity%>"
           size="16" type="text">
        <div class="pull-left">
          <button class="btn" type="button"><i class="icon-minus"></i>
          </button>
          <button class="btn" type="button"><i class="icon-plus"></i>
          </button>
          <button class="btn btn-danger" type="button">
            <i class="icon-remove icon-white"></i>
          </button>
        </div>
      </div>
    </td>
    <td class="col-md-1"><%= number_to_currency(a.product.export_price, unit: "$", precision: 0, format: "%u %n") %></td>
    <td class="col-md-1"><%= a.product.sale %></td>
    <td class="col-md-1"><%= number_to_currency(a.total_price, unit: "$", precision: 0, format: "%u %n")%></td>
  </tr>
<% end %>
<tr>
  <td>
    <%= link_to cart_path(@cart), {:method => :delete, class: 'btn btn-warning', style: "margin-top: 10%;"},
      data: {:confirm => t("mess_delete")} do %>
      <i ><%= t "view_cart.btn_empty_cart" %></i>
    <% end %>
  </td>
  <td colspan="5" style="text-align:right">
    <%= number_to_currency(current_cart.total_price, unit: "$", precision: 0, format: "%u %n") %>
  </td>
</tr>

app/views/carts/_search.html.erb
<%= form_tag search_path, class: "form-inline navbar-search", method: :get do %>
  <%= text_field_tag 'text', params[:text],
    placeholder: t("product.text_search"), class: "srchTxt" %>
  <%= submit_tag "     ", id: "srchFld" %>
<% end %>

app/views/carts/_show_product_cart.html.erb
<%= current_cart.line_items.each do |a| %>
  <tr>
    <td>
      <%= link_to image_tag("products/6.jpg") %>
     <img width="60" src="themes/images/products/4.jpg" alt=""/></td>
    <td><%= a.product.name %><br/>Color : black, Material : metal</td>
    <td>
    <div class="input-append">
      <input class="span1" style="max-width:34px" placeholder="1"
        id="appendedInputButtons" size="16" type="text">
      <button class="btn" type="button"><i class="icon-minus"></i>
      </button>
      <button class="btn" type="button"><i class="icon-plus"></i>
      </button>
      <button class="btn btn-danger" type="button">
        <i class="icon-remove icon-white"></i>
      </button>
    </div>
    </td>
    <td><%= a.product.export_price %></td>
    <td>$25.00</td>
    <td>$15.00</td>
    <td>$110.00</td>
  </tr>
<% end %>

app/views/carts/index.html.erb
<% if notice %>
  <div class="alert alert-primary" role="alert">
    <%= notice %>
  </div>
<% end %>
<div id="mainBody">
  <div class="container">
  <div class="row">
<div class="span9">
<p id="notice"><%= notice %></p>
<%= render "search" %>
  <table width="100%">
    <thead>
      <th>Name product</th>
      <th>Import price</th>
      <th>Export price</th>
      <th>Sale</th>
      <th colspan="2"></th>
    </thead>
    <% @product.each do |product| %>
      <tbody>
        <td><%= product.name %></td>
        <td style="text-align: center;" ><%= product.import_price %></td>
        <td style="text-align: center;" ><%= product.export_price %></td>
        <td style="text-align: center;" ><%= product.sale %></td>
        <td style="text-align: center;" ><%= link_to "Hiển thị", product, class: "btn btn-primary", target: "_blank" %></td>
        <td>
 <%= button_to "Thêm vào giỏ hàng", line_items_path(product_id: product), class: "btn btn-primary", remote: true %>
        </td>
      </tbody>
    <% end %>
  </table>
  <%= paginate @product, theme: "twitter-bootstrap", window: 3 %>
      </div>
    </div>
  </div>
</div>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<div id="mainBody">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <% if notice %>
  <div class="alert alert-primary" role="alert">
    <%= notice %>
  </div>
<% end %>
        <ul class="breadcrumb">
        <li><a href="index.html"><%= t "view_cart.home" %></a> <span class="divider">/</span></li>
        <li class="active"><%= t "view_cart.shopping_cart" %></li>
        </ul>
        <h3><%= t "view_cart.shopping_cart" %>[ <small>3 <%= t "view_cart.item" %></small>]
          <%= link_to root_path, class: "btn btn-large pull-right" do %>
            <i class="icon-arrow-left"></i><%= t "view_cart.btn_continue_shopping" %>
          <% end %>
        </h3>
        <hr class="soft"/>
        <div id="cart">
          <% if hide_cart_if? %>
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th><%= t "view_cart.product" %></th>
                  <th><%= t "view_cart.description" %></th>
                  <th><%= t "view_cart.quantity" %></th>
                  <th><%= t "view_cart.price" %></th>
                  <th><%= t "view_cart.sale" %></th>
                  <th><%= t "view_cart.total" %></th>
                </tr>
              </thead>
              <tbody>
              <%= render @cart %>
                <tr>
                  <td>

                    <%= button_to @cart, {:method => :delete, class: 'btn btn-warning', style: "margin-top: 10%;"},
                      data: {:confirm => t("mess_delete")} do %>
                      <i ><%= t "view_cart.btn_empty_cart" %></i>
                    <% end %>
                  </td>
                  <td colspan="5" style="text-align:right">
                    <%= number_to_currency(current_cart.total_price, unit: "$", precision: 0, format: "%u %n") %>
                  </td>
                </tr>
              </tbody>
            </table>
            <%= link_to new_order_path, method: :get, class: "btn btn-info pull-right"  do %>
              <i class="icon-arrow-right"></i> <%= t "view_cart.btn_next" %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>