config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
    root "static_pages#index"
    get "sessions/new"
    get "/index", to: "static_pages#index"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    get "/admin", to: "products#index"
    post "/login", to: "sessions#create"
    post "/signup", to: "users#create"
    delete "/logout", to: "sessions#destroy"
    post "/line_item", to: "line_items#create"
    # post "/product", to: "products#create"
    get "/product_details", to: "static_pages#product_details"
    get "admin/admin"
    get "admin/index"
    get "/checkorder", to: "line_items#index"
    get "/check", to: "line_items#show"
    get "/search", to: "static_pages#index"
    get "/change_quantity/:id", to: "line_items#change_quantity"
    get "/show_code_order", to: "orders#show_code_order"
    get "/show_order", to: "orders#show"
    post "/order_status", to: "orders#update"
    get "/create_order", to: "carts#index"
    resources :carts
    resources :products
    resources :users
    resources :orders
    resources :line_items
    resources :feedbacks
end

app/models/product.rb
class Product < ApplicationRecord
  paginates_per 10
  has_many :images
  has_many :feedbacks
  has_many :detail_bills
  has_many :order_products
  has_many :product_categorys
  has_many :line_items
  before_destroy :check_if_has_line_item
  scope :search_product,
    ->(name_product){where(Product.arel_table[:name].lower.matches(name_product.downcase))}
  # scope :search_product_describe,
  # ->(describe_product){where(Product.arel_table[:describe].lower.matches(describe_product.downcase))}
  scope :order_desc, ->{order created_at: :desc}
  private

  def check_if_has_line_item
    return true if line_items.empty?
    return false if errors.add(:base, "This product has a LineItem")
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include LineItemsHelper
  before_action :authentication?, except: :show
  before_action :admin_user, only: %i(destroy)
  before_action :search_product, only: %i(edit update)

  def index
    @product = Product.all.order('created_at DESC').page params[:page]
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params

    if @product.save
      @product.images.create image: "laptop/#{rand(1..8)}.jpg"
      flash[:info] = t "success"
      redirect_to admin_path
    else
      render :new
    end
  end

  def show
    @product_detail = Product.find_by id: params[:id]
    @img = Image.find_by(product_id: @product_detail)
    return if @product_detail && @img
    redirect_to root_path
    @find = current_cart.line_items
    @show_product_cart = Product.find_by id: @find
  end

  def edit; end

  def update
    @product = Product.find_by id: params[:id]

    if @product.update_attributes product_params
      flash[:success] = t "success"
      redirect_to admin_path
    else
      flash[:danger] = t "no_success"
      render :new
    end
  end

  def destroy
    @product = Product.find_by id: params[:id]

    if @product.destroy
      flash[:success] = t("success")
    else
      flash[:danger] = t("no_success")
    end
    redirect_to admin_path
  end

  private

  def product_params
    params.require(:product).permit :name, :import_price,
      :export_price, :describe, :note, :status, :image, :time_guaranate, :sale
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end

  def search_product
    return if @product = Product.find_by(id: params[:id])
    flash[:success] = t "not_found_product"
    redirect_to admin_path
  end

  def authentication?
    redirect_to root_path unless current_user
  end
end

app/views/products/_product_form.html.erb
<%= form_with model: @product do |f| %>
<div class="row">
  <div class="col-lg-4">
    <div class="form-group">
      <%= f.label :name, "Tên sản phẩm" %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :import_price, "giá nhập" %>
      <%= f.number_field :import_price, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :export_price, "giá bán" %>
      <%= f.number_field :export_price, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :note, "Ghi chú" %>
      <%= f.text_field :note , class: 'form-control'%>
    </div>

    <div class="form-group">
      <%= f.label :status, "trạng thái" %>
      <%= f.select :status, options_for_select([["Avaiable", 1], ["Sold out", 0]]), class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :image, "Hình ảnh" %>
      <% if !@product.new_record? %>
        <%= image_tag(@product.images.first.image, size: 100) %>
      <% else %>
        <%= f.file_field :image, class: 'form-control-file' %>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :time_guaranate, "Thời gian bảo hành" %>
      <%= f.text_field :time_guaranate, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :sale, t("sale") %>
      <%= f.number_field :sale , class: 'form-control'%>
    </div>
  </div>
      <div class="col-lg-8">
    <div class="field">
      <%= f.label :describe, "Miêu tả" %><br>
      <%= f.text_area :describe, class: "ckeditor" %>
    </div>
  </div>
</div>
  <div class="form-group pull-right">
    <%= f.submit "Thêm", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/_product_row.html.erb
<% @products.each do |product| %>
  <div class="col-md-4">
    <div class="thumbnail">
    <%= link_to image_tag(product.images.first.image, alt: "register.html", class: 'product-thumnail'), product %>
    <div class="caption">
      <h5 data-id="<%= product.id %>"><%= product.name %></h5>
      <p>
      </p>
      <h4 style="text-align:center">
        <a class="btn" href="<%= product_path product.id %>"><i class="icon-zoom-in"></i></a>
        <%= button_to  line_items_path(:product_id => product), class: "btn", remote: true do %>
        <i class="icon-shopping-cart"></i>
        <% end %>
        <a class="btn btn-primary" href="#">
          <%= number_to_currency(product.export_price, unit: "$", precision: 0, format: "%u %n") %>
        </a>
      </h4>
    </div>
    </div>
  </div>
<% end %>

app/views/products/_search.html.erb
<%= form_tag search_path, class: "form-inline form-group navbar-search", method: :get do %>
  <%= text_field_tag 'text', params[:text],
    placeholder: t("product.text_search"), class: "srchTxt form-control form-control-lg" %>
  <%= submit_tag "     ", id: "srchFld" %>
<% end %>

app/views/products/edit.html.erb
<% provide :button_text, t("save_changes") %>
<div class="container">
<div class="row">
  <div class='col-md-3'></div>
  <div class="col-md-6">
    <%= render "products/product_form" %>
  </div>
</div>
</div>

app/views/products/index.html.erb
<div id="mainBody">
<div class="container">
<div class="row">
<div class="right_col" role="main">
  <div class="col-md-12">
    <div class="page-title">
      <div class="title_left">
        <h3><%= t "danhsachsp" %></h3>
      </div>
    </div>
    <div class="clearfix"></div>
      <div>
        <div class="col-md-12 col-sm-12 col-xs-12">
          <ul class="nav navbar-right panel_toolbox">
            <li><a href=""></a></li>
            <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
            <li><a class="close-link"><i class="fa fa-close"></i></a></li>
          </ul>
        <div class="clearfix"></div>
        </div>
        <div class="x_content">

          <div class="form-group">
            <%= link_to t("add"), "products/new", class: "btn btn-primary"%>
            </div>
          <table id="datatable" class="table table-striped table-bordered table-hover">
            <thead>
            	<tr>
                <th scope='col'><%= t "ten" %></th>
                <th scope='col'><%= t "idhinhanh" %></th>
                <th scope='col'><%= t "gianhap" %></th>
                <th scope='col'><%= t "giaxuat" %></th>
                <th scope='col'><%= t "mieuta" %></th>
                <th scope='col'><%= t "ghichu" %></th>
                <th scope='col'><%= t "trangthai" %></th>
                <th scope='col'><%= t "time" %></th>
                <th scope='col'><%= t "sale" %></th>
                <th scope='col'><%= t "action" %></th>
              </tr>
            </thead>
            <tbody>
            <% @product.each do |y| %>
              <tr>
                <td><%= y.name %></td>
                <td><%= image_tag(y.images.first&.image, size: 50) %></td>
                <td><%= number_to_currency(y.import_price, unit: "$", precision: 0, format: "%u %n") %></td>
                <td><%= number_to_currency(y.export_price, unit: "$", precision: 0, format: "%u %n") %></td>
                <td><%= y.describe.html_safe %></td>
                <td><%= y.note %></td>
                <td>
                  <% if y.status == 1 %>
                    <span class="badge-success badge  "> Avaiable</span>
                  <% else %>
                  <span class="badge badge-warning"> Sold out</span>
                  <% end %>
                </td>
                <td><%= y.time_guaranate %></td>
                <td><%= y.sale.to_s << '%' %></td>
                <td>
                  <%= link_to t("edit"), edit_product_path(y), class: "btn btn-primary" %>
                  <%= link_to t("delete"), y, method: :delete, class: "btn btn-danger"%>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>

          <div class="container pagination justify-content-center" >
            <%= paginate @product, theme: 'twitter-bootstrap-4', pagination_class: "pagination-sm" %>
          </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/products/new.html.erb
<% provide :button_text, "Create" %>
<div class="container">

    <%= render "products/product_form" %>

</div>