config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
    root "static_pages#index"
    get "sessions/new"
    get "/index", to: "static_pages#index"
    get "/signup", to: "users#new"
    get "/login", to: "sessions#new"
    get "/admin", to: "products#index"
    post "/login", to: "sessions#create"
    post "/signup", to: "users#create"
    delete "/logout", to: "sessions#destroy"
    post "/line_item", to: "line_items#create"
    # post "/product", to: "products#create"
    get "/product_details", to: "static_pages#product_details"
    get "admin/admin"
    get "admin/index"
    get "/checkorder", to: "line_items#index"
    get "/check", to: "line_items#show"
    get "/search", to: "static_pages#index"
    get "/change_quantity/:id", to: "line_items#change_quantity"
    get "/show_code_order", to: "orders#show_code_order"
    get "/show_order", to: "orders#show"
    post "/order_status", to: "orders#update"
    get "/create_order", to: "carts#index"
    resources :carts
    resources :products
    resources :users
    resources :orders
    resources :line_items
    resources :feedbacks
end

app/views/layouts/_carouseBlk.html.erb
<div id="carouselBlk">
  <div id="myCarousel" class="carousel slide" data-interval="100">
    <div class="carousel-inner">
      <div class="item active">
      <div class="container">
      <%= link_to image_tag("macbook/1.jpg", all:"special offers", class: "banner"), "register.html" %>
      <div class="carousel-caption">
          <h4>Second Thumbnail label</h4>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </div>
      </div>
      </div>
      <div class="item">
      <div class="container">
      <%= link_to image_tag("macbook/2.jpg", all:"special offers", class: "banner"), "register.html" %>
        <div class="carousel-caption">
          <h4>Second Thumbnail label</h4>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </div>
      </div>
      </div>
      <div class="item">
      <div class="container">
      <%= link_to image_tag("macbook/3.jpg", all:"special offers", class: "banner"), "register.html" %>
      <div class="carousel-caption">
          <h4>Second Thumbnail label</h4>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </div>

      </div>
      </div>
       <div class="item">
       <div class="container">
      <%= link_to image_tag("macbook/4.jpg", all:"special offers", class: "banner"), "register.html" %>
      <div class="carousel-caption">
          <h4>Second Thumbnail label</h4>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
        </div>

      </div>
      </div>
       <div class="item">
       <div class="container">
      <%= link_to image_tag("macbook/5.jpg", all:"special offers", class: "banner"), "register.html" %>
      <div class="carousel-caption">
          <h4>Second Thumbnail label</h4>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
      </div>
      </div>
      </div>

    </div>
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
</div>

app/views/layouts/_cart_info_header.html.erb
  <%= link_to "product_summary.html" do %>
  <% end %>
  <span class="btn btn-mini"><%= number_to_currency(current_cart.total_price, unit: "$", precision: 0, format: "%u %n") %></span>
  <%= link_to  "#"  do %><span class=""></span><% end %>
  <%= link_to cart_path(current_cart.id) do %><span class="btn btn-mini btn-primary">
    <i class="icon-shopping-cart icon-white"></i>
    [ <%= current_cart.line_items.sum(:quantity) %> ] sản phẩm</span>
<% end %>

app/views/layouts/_cart_info_sidebar.html.erb
<%= link_to  id: "myCart" do %>
  <%= link_to image_tag("ico/ico-cart.png", alt: "cart"), cart_path(current_cart) %>
  <%= current_cart.line_items.sum(:quantity) %>
   Items in cart
  <span class="badge badge-warning pull-right"><%= number_to_currency(current_cart.total_price, unit: "$", precision: 0, format: "%u %n") %></span>
<% end %>

app/views/layouts/_footer.html.erb
  <div  id="footerSection">
  <div class="container">
    <p class="pull-right">&copy; LAPTOP</p>
  </div><!-- Container End -->
  </div>

app/views/layouts/_head.html.erb
<meta charset="utf-8">
<title>Hiếu</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="themes/images/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="themes/images/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="themes/images/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="themes/images/ico/apple-touch-icon-57-precomposed.png">

<%= stylesheet_link_tag "application", media: "all",
  "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload", defer: true %>

app/views/layouts/_header.html.erb
<div id="header">
<div class="container">
<div id="welcomeLine" class="row">
  <div class="col-md-6"></div>
  <div class="col-md-6">
  <div class="pull-right cart-info-header">
    <%= render 'layouts/cart_info_header' %>
  </div>
  </div>
</div>
<!-- Navbar ================================================== -->
<div id="logoArea" class="navbar">
<a id="smallScreen" data-target="#topMenu" data-toggle="collapse" class="btn btn-navbar">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>
  <div class="navbar-inner">
    <%= link_to "Hiếu", root_path , id: "brand", class: "navbar-brand faded", method: :get %>
    <%= render "products/search" %>
    <ul id="topMenu" class="nav pull-right">
      <% if logged_in? %>
        <% if session[:admin] %>

          <li class="">
            <%= link_to "Liên hệ", new_feedback_path %>
          </li>
          <li><%= link_to "Quản lý đơn hàng", orders_path %></li>
          <li><%= link_to "Quản lý sản phẩm", admin_path %></li>

          <li><%= link_to "Tạo đơn hàng", create_order_path(id: current_cart) %></li>
        <% else %>
          <li class="">
            <%= link_to "Liên hệ", new_feedback_path %>
          </li>
          <li class="">
            <%= link_to "Kiểm tra đơn hàng", checkorder_path %>
          </li>
        <% end %>
          <li><%= link_to "Đăng xuất", logout_path, method: :delete %></li>
      <% else %>
        <li class="">
          <%= link_to "Liên hệ", new_feedback_path %>
        </li>
        <li class="">
          <%= link_to "Kiểm tra đơn hàng", checkorder_path %>
        </li>
        <li><%= link_to "signup.html" do %>đăng ký<% end %></li>
        <li class="">
        <li><%= link_to "Đăng nhập", login_path %></li>
        <div id="login" class="modal hide fade in" tabindex="-1" role="dialog"
          aria-labelledby="login" aria-hidden="false" >
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal"
              aria-hidden="true">×</button>
            <h3><%= t "title_login" %></h3>
          </div>
          <%= render "layouts/login" %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
</div>
</div>
</div>

app/views/layouts/_login.html.erb
<div class="modal-body">
  <%= form_for(:session, url: login_path) do |f| %>

    <%= f.label :email %>
    <%= f.email_field :email, class: "control-group" %>
    
    <%= f.label :password %>
    <%= f.password_field :password, class: "control-group" %>
    <br>
    <%= f.submit t("btn_sign_in"), class: "btn btn-success" %>
    <%= f.submit t("btn_lose"), class: "btn", data: {dismiss: "modal"}, aria: {hidden: "true"} %>
  <% end %>
</div>

app/views/layouts/_sidebar.html.erb
<div id="sidebar" class="col-md-3">
  <div class="well well-small cart-info-sidebar">
    <%= render 'layouts/cart_info_sidebar' %>
  </div>
  <ul id="sideManu" class="nav nav-tabs nav-stacked">
    <li class="subMenu open"><a> LAPTOP [<%= Product.count %>]</a>
      <ul>
        <li>
          <%= link_to "../search?describe=dell", class: "active" do %>
            <i class="icon-chevron-right"></i>DEL (100)
          <% end %>
        </li>
        <li>
          <%= link_to "../search?describe=ASUS" do %>
            <i class="icon-chevron-right"></i>ASUS (30)
          <% end %>
        </li>
        <li>
          <%= link_to "../search?describe=LENOVO" do %>
            <i class="icon-chevron-right"></i>LENOVO (80)
          <% end %>
        </li>
      </ul>
    </li>
    <li class="subMenu"><a> ACCESSORIES [120] </a>
      <ul style="display:none">
        <li>
          <%= link_to "products.html" do %>
            <i class="icon-chevron-right"></i>RAM (45)
          <% end %>
        </li>
        <li>
          <%= link_to "products.html" do %>
          <i class="icon-chevron-right"></i>ROM (8)
          <% end %>
        </li>
      </ul>
    </li>
  </ul>
  <br/>
  <div class="thumbnail">
  <%= link_to image_tag(Product.last.images.first.image,
    alt: "Bootshop panasonoc New camera") %>
  <div class="caption">
    <h5><%= Product.last.name %></h5>
    <h4 style="text-align:center">
      <a class="btn" href="<%= product_path Product.last %>">
        <i class="icon-zoom-in"></i>
      </a>
      <a class="btn" href="#"><%= t "btn_add" %><i class="icon-shopping-cart"></i>
      </a>
      <a class="btn btn-primary" href="#"><%= number_to_currency(Product.last.export_price, unit: "$", precision: 0, format: "%u %n") %> </a>
    </h4>
  </div>
  </div><br/>
  <div class="thumbnail">
    <%= link_to image_tag(Product.first.images.first.image,
      alt: "Bootshop panasonoc New camera", title: "Bootshop New Kindel") %>
    <div class="caption">
      <h5><%= Product.first.name %></h5>
        <h4 style="text-align:center">
          <a class="btn" href="<%= product_path Product.first %>">
            <i class="icon-zoom-in"></i>
          </a>
          <a class="btn" href="#"><%= t "btn_add" %>
            <i class="icon-shopping-cart"></i>
          </a>
          <a class="btn btn-primary" href="#"><%= number_to_currency(Product.first.export_price, unit: "$", precision: 0, format: "%u %n") %> 
          </a>
        </h4>
    </div>
    </div><br/>
  <div class="thumbnail">
    <%= link_to image_tag("payment_methods.png",
      alt: "Bootshop panasonoc New camera", title: "Bootshop New Kindel") %>
    <div class="caption">
      <h5>Payment Methods</h5>
    </div>
  </div>
</div>

app/views/layouts/_signup.html.erb
<div class="span9">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, t "confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/head" %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>